[package]
name = "aoc_day1"
version = "0.0.1"
authors = [
    "Ian Aksum <ian.aksum@gmail.com",
]
edition = '2021'


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build]
target = "aarch64"

[dependencies]
regex = "1.10.2"

